### PR TITLE
Changed the split locations

### PR DESCRIPTION
**Pull request by derekwyatt**
- I like my screen vertically split around 70/30, not 50/50
- So I put together a simple preferences addition that allows for the
  customization of the splits, both vertically and horizontally
- As well, the 1/3, 2/3 split alternatives might seem weird with
  alternative splits so I provided a customization here too; you can
  enable the feature or not.

### CODE REVIEW

**Comment by ameyec** [comment]
This by itself would be a useful addition. 
It appears the build fails with (clicking on 'Details' of the travis-ci build link above) 

`/Users/travis/build/fikovnik/ShiftIt/ShiftIt/Base.lproj/PreferencesWindow.xib: error: The document "(null)" requires Xcode 8.0 or later.`

https://docs.travis-ci.com/user/osx-ci-environment/

**Comment by fikovnik** [comment]
Thanks a lot for this. What I think would be useful is to be able to to use the same key shortcut to iterate over different sizes. By pressing shortcut for left the window changes to 1/2, 1/3, 2/3.

**Comment by derekwyatt** [comment]
Sorry... just getting back to this now. @fikovnik Would that not be a decent candidate for a different PR? I wouldn't want the two features to get jammed up together into (what should be) a single commit.  No?

**Comment by derekwyatt** [comment]
I still can't get this to pass in travis.  I don't know jack about building for Xcode or OSX... or Travis for that matter. I've tried changing the `osx_image` a few times but it fails for other interesting reasons when I do that:
```
ERROR: Unexpected action: build

The command "xctool -project ShiftIt/ShiftIt.xcodeproj -scheme ShiftIt build test" exited with 4.
```

**Pull request closed without merging**
