### PR TITLE
Keeps the 1/2->1/3->2/3 window behavior, but resets the cycle anytime…

### PR DESCRIPTION
**Pull request by kjrokos**
… a window is moved outside of the cycle

### CODE REVIEW

**Comment by rca** [comment]
I'm confused.  I have no idea what the `develop` branch has or how out of date it is.  The last commit is from 2016/10/19.  Version 1.6.4, which contains the shifty behavior, was cut from the `master` branch.

Would you mind applying your patches to a branching off `master`.

Thanks

**Comment by kjrokos** [comment]
Sure -- I actually had it on master originally, and then noticed the README said all development was off of the develop branch

**Comment by kjrokos** [comment]
Reopened as #258

**Comment by rca** [comment]
:(  I may be giving you bad direction; I'm a noob to this project.  However, I do know for a fact that master contains the bad code, and I think `develop` is stale.

Let's pick up the README inconsistency in another issue.

**Pull request closed without merging**
