### PR TITLE
Add some great new features for ultra wide monitors

### PR DESCRIPTION
**Pull request by allanragec**
Add some great new features for ultra wide monitors:

# **Divided by 6**

Screen Shot 2020-06-04 at 23 43 59

- Left Third Top
- Left Third Bottom
- Center Third Top
- Center Third Bottom
- Right Third Top
- Right Third Bottom

# **Divided by 3**

Screen Shot 2020-06-04 at 23 43 21

- Left Third
- Center Third
- Right Third

Jun-04-2020 23-34-46

### CODE REVIEW

**Comment by fikovnik** [comment]
Thanks a lot! I don't know if you have seen https://github.com/fikovnik/ShiftIt/issues/296, but I no longer use OSX so I cannot even test this. If you want I could add you to the project if you would like to take over.

**Comment by allanragec** [comment]
@fikovnik Yeah, I saw that, I sorry about it. I'm using ShiftIt app for a long time and I can't imagine myself without this app. Instead to pay for other apps to have these features, I preferred to send this PR to have it and I'm loving to use these new features in my local machine. Would be a honor to be a maintainer :D

**Comment by sposmen** [comment]
@fikovnik would be great a new maintainer like @allanragec ... I also use it in the MacOS 10.15.x versions and this new feature would be awesome too in my 43" monitor. 🙏🏻

**Comment by fikovnik** [comment]
Indeed it would! I have just sent @allanragec an invite to the repo! Thanks a lot!

**Comment by allanragec** [comment]
@rca the default locations are: 
image

**Comment by hbto** [comment]
@allanragec awesome work

**Comment by gsingh93** [comment]
Can a new release be created which includes this PR?

**Comment by JaKXz** [comment]
@allanragec sorry to ping out of the blue on a closed PR, but yeah would love to see a new version published with this cool stuff! :)

**Comment by Antiavanti** [comment]
> @allanragec sorry to ping out of the blue on a closed PR, but yeah would love to see a new version published with this cool stuff! :)

@allanragec I came here to put the same question, could you create a new release `1.6.7` from current master? I think this PR is definitely worth to be released as soon as possible, because since last release from 2018 this one is a game changer, no doubts :)

**Pull request merged**
