### PR TITLE
Release env

### PR DESCRIPTION
**Pull request by rca**
In order to help with #246, I'm attempting to generate a release and am running into a few issues:

- [x] hardcoded paths to github token and signing key in `fabfile.py`
- [x] trying to make it easier to setup a build / release environment
- [x] get the signing DSA key from Filip
- [x] overcome the error below

I do not know how to make the DSA key used for signing the release.

When running `fab release` I get this error and am not sure how to proceed:

```
[berto@g6]$ fab release
[localhost] local: defaults read /Users/berto/Projects/ShiftIt/ShiftIt/ShiftIt-Info.plist CFBundleVersion
[localhost] local: git diff-index --quiet HEAD --
Warning: there are pending changes in the repository. Run git status
Traceback (most recent call last):
  File "/Users/berto/.virtualenvs/shiftit/lib/python2.7/site-packages/fabric/main.py", line 757, in main
    *args, **kwargs
  File "/Users/berto/.virtualenvs/shiftit/lib/python2.7/site-packages/fabric/tasks.py", line 426, in execute
    results['<local-only>'] = task.run(*args, **new_kwargs)
  File "/Users/berto/.virtualenvs/shiftit/lib/python2.7/site-packages/fabric/tasks.py", line 173, in run
    return self.wrapped(*args, **kwargs)
  File "/Users/berto/Projects/ShiftIt/fabfile.py", line 246, in release
    milestone = _get_milestone()
  File "/Users/berto/Projects/ShiftIt/fabfile.py", line 95, in _get_milestone
    raise Exception('Unable to find milestone: %s' % proj_version)
Exception: Unable to find milestone: 1.6.3
```

### CODE REVIEW

**Comment by b-long** [comment]
Seems like a smart idea.  

@fikovnik Any thoughts?

**Comment by fikovnik** [comment]
@rca - if you agree and can add you to this repository and share with you the keys - I will only need you public pgp key. 

Regarding the error - the script is trying get closed ticket in a GH milestone. The current milestone comes from the plist https://github.com/fikovnik/ShiftIt/blob/master/ShiftIt/ShiftIt-Info.plist Since there is no open milestone if fails. The plist has to be changed. That information is also propagated to the about dialog in the app.

**Comment by rca** [comment]
@fikovnik sure; let's give this a shot.

Public key at: https://gist.github.com/rca/c8040ec81d0e6bdd1ef2824ff797c664

**Comment by fikovnik** [comment]
Thanks a lot! I added you as a contributor and sent the keys.

**Comment by rca** [comment]
@fikovnik please review this PR and the release below:

https://github.com/fikovnik/ShiftIt/releases/tag/version-1.6.4

Thanks!

**Comment by rca** [comment]
Note to others that land on this PR: the DSA key is project-specific and I got it directly from Filip.

**Comment by fikovnik** [comment]
Excellent work! Thanks a lot!

It would be also great to update [homebrew](https://github.com/caskroom/homebrew-cask/blob/0e1d323f7c156e029c5ceb99e4510445280d4233/Casks/shiftit.rb) in the case somebody is installing shift via homebrew cask.

**Pull request merged**
